### PR TITLE
docs: Commit early, commit often

### PR DESCRIPTION
**Pull request by CjHare**

### CODE REVIEW

**Comment by CjHare** [comment]
This template repo, besides being a GitHub template can also acts as a single source of truth (i.e. a single place) for our (WindRanger) development processes.

My initial idea is to involve the entire dev team, get discussions moving and achieve a consensus on our take of best practices that we'll use across our products.

Why have you been added as a reviewer? ...well, that's because you're part of the WindRanger dev team and I'd greatly appreciate your input on this change about how we use git.

As always, question & feedback are welcome 🙂

**Comment by bitparadigm** [comment]
We can iteratively updates this template repo. Otherwise initially looks okay. Just usual Solidity, TypeScript, Git, environment code styles.  https://gist.github.com/ericavonb/3c79e5035567c8ef3267 https://docs.soliditylang.org/en/v0.5.3/style-guide.html

**Review by shahankhatch — APPROVED** [review]
I recommend moving the development process content into a CONTRIBUTING.md file in the root of the project.

**Comment by CjHare** [comment]
> We can iteratively updates this template repo. Otherwise initially looks okay. Just usual Solidity, TypeScript, Git, environment code styles. https://gist.github.com/ericavonb/3c79e5035567c8ef3267 https://docs.soliditylang.org/en/v0.5.3/style-guide.html

Iteratively updating is plan for this repo 👍 

In terms of Solidity code style, there's an open issue to add a [Pretty plugin](https://github.com/windranger-io/solidity-project-template/issues/4) for Solidity (hopefully it'll default to the Solidity docs standard, but if not it can be made to replicate it)

**Pull request merged**
